# Site settings
title: slothbucket
email: jimmy@slothbucket.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://slothbucket.com" # the base hostname & protocol for your site
github_username:  jimmyshen

# Build settings
markdown: kramdown
